version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pulsebot-db
    restart: always
    environment:
      POSTGRES_DB: pulsebot
      POSTGRES_USER: pulsebot_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Auto-load schema
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulsebot_user -d pulsebot"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  pgdata: